# Generated by Django 4.1.7 on 2023-03-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.TextField(max_length=10)),
                ('branch', models.TextField(max_length=10)),
                ('section', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('period', models.IntegerField()),
                ('R19R11A05B0', models.TextField()),
                ('R19R11A05B1', models.TextField()),
                ('R19R11A05B2', models.TextField()),
                ('R19R11A05B3', models.TextField()),
                ('R19R11A05B4', models.TextField()),
                ('R19R11A05B5', models.TextField()),
                ('R19R11A05B6', models.TextField()),
                ('R19R11A05B7', models.TextField()),
                ('R19R11A05B8', models.TextField()),
                ('R19R11A05C9', models.TextField()),
                ('R20R15A0513', models.TextField()),
                ('R19R11A0516', models.TextField()),
            ],
        ),
    ]
