# Generated by Django 4.1.7 on 2023-03-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='R19R11A0516',
            field=models.TextField(default='absent'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='R19R11A05B0',
            field=models.TextField(default='absent'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='R19R11A05B1',
            field=models.TextField(default='absent'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='R19R11A05B2',
            field=models.TextField(default='absent'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='R19R11A05B3',
            field=models.TextField(default='absent'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='R19R11A05B4',
            field=models.TextField(default='absent'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='R19R11A05B5',
            field=models.TextField(default='absent'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='R19R11A05B6',
            field=models.TextField(default='absent'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='R19R11A05B7',
            field=models.TextField(default='absent'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='R19R11A05B8',
            field=models.TextField(default='absent'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='R19R11A05C9',
            field=models.TextField(default='absent'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='R20R15A0513',
            field=models.TextField(default='absent'),
        ),
    ]
