# Generated by Django 4.1.7 on 2023-03-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark', '0002_alter_attendance_r19r11a0516_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='R19R11A04C2',
            field=models.TextField(default='absent'),
        ),
    ]
