# Generated by Django 4.1.7 on 2023-04-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark', '0003_attendance_r19r11a04c2'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='R160220735070',
            field=models.TextField(default='absent'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='R160220735077',
            field=models.TextField(default='absent'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='R160220735088',
            field=models.TextField(default='absent'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='R160220735090',
            field=models.TextField(default='absent'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='R160220735120',
            field=models.TextField(default='absent'),
        ),
    ]
